feat: refine pre-commit string

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -1,6 +1,13 @@
+eslint . --fix
+if [ $? -ne 0 ]; then
+  echo "Lint errors detected. Please fix them before committing."
+  exit 1
+fi
+
+
 #!/bin/sh
 branch="$(git rev-parse --abbrev-ref HEAD)"
-if [ "$branch" = "main" ]; then
-  echo "You can't commit directly to main branch"
+if [ "$branch" = "main" ] || [ "$branch" = "staging" ]; then
+  echo "You can't commit directly to the $branch branch"
   exit 1
 fi
